name: flow_sketch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - meshio
  - gmsh
  - su2
  - pytorch
  - torchvision
  - fastapi
  - uvicorn
  - pydantic
